builds:
  - binary: fdn
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/hobbymarks/fdn/cmd.version={{.Version}}
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: fdn
    homepage: "https://github.com/hobbymarks/fdn"
    tap:
      owner: hobbymarks
      name: homebrew-hobbymarks
    commit_author:
      name: hobbymarks
      email: ihobbymarks@gmail.com

checksum:
  name_template: "checksums.txt"
