version: 2

before:
  hooks:
    - go mod tidy
    - go mod vendor

release:
  prerelease: auto

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/hobbymarks/fdn/cmd.version={{.Version}}
    ignore:
      - goos: darwin
        goarch: '386' # macOS doesn't run on 386

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'


brews:
  - repository:
      owner: hobbymarks
      name: release
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/hobbymarks/fdn"
    description: "File and directory name normalizer with rollback"
    license: "MIT"
    directory: Formula
    install: |
      bin.install "fdn"

scoops:
  - repository:
      owner: hobbymarks
      name: release
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/hobbymarks/fdn"
    description: "File and directory name normalizer with rollback"
    license: "MIT"
    directory: bucket

nfpms:
  - id: fdn
    package_name: fdn
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    maintainer: "hobbymarks <ihobbymarks@gmail.com>"
    description: "File and directory name normalizer with rollback"
    homepage: "https://github.com/hobbymarks/fdn"
    license: "MIT"

aurs:
  - name: fdn
    homepage: "https://github.com/hobbymarks/fdn"
    description: "File and directory name normalizer with rollback"
    maintainers:
      - "hobbymarks <ihobbymarks@gmail.com>"
    license: "MIT"
    directory: aur-fdn
