{% set ver = "2022.4.25" %}
{% set num = "2819" %}

package:
    name: fdn
    version: {{ ver }}

build:
    number: {{ num }}
    skip: True # [py<38]
    entry_points:
        - fdn = fdn:run_main

source:
    url: "https://pypi.io/packages/source/f/fdn/fdn-{{ ver }}.{{ num }}.tar.gz"

requirements:
    build:
        - python
        - setuptools
    
    host:
        - python
        - setuptools
    
    run:
        - 'python>=3.8'
        - 'click>=8.0.0'
        - 'setuptools>=49.6.0'
        - 'unidecode>=1.2.0'
        - 'cryptography>=3.4.7'
        - 'nltk>=3.6.2'
        - 'colorama>=0.4.4'
        - 'pandas>=1.2.4'
        - 'wcwidth>=0.2.5'

about:
    home: https://github.com/hobbymarks/fdn.git
    description: A tool for uniformly changing file or directory names.
    doc_source_url: https://github.com/hobbymarks/fdn/blob/main/README.rst
    license: MIT
    license_file: LICENSE
