{% set version = "0.8.2" %}

package:
    name: ufn
    version: { { version } }

build:
    skip: True # [py<38]

source:
    git_url: https://github.com/hobbymarks/UFn.git

requirements:
    build:
       - python
       - setuptools
    host:
       - python
       - setuptools

    run:
        - 'python>=3.8'
        - 'click~=7.1.2'
        - 'setuptools>=49.6.0'
        - 'unidecode>=1.2.0'
        - 'cryptography>=3.4.7'
        - 'nltk>=3.6.2'
        - 'colorama>=0.4.4'
        - 'pandas>=1.2.4'
        - 'wcwidth>=0.2.'

about:
    home: https://github.com/hobbymarks/UFn.git
    description: 
    license: MIT
    license_file: LICENSE
